apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-movies
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Release.Name }}-movies
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Release.Name }}-movies
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: movies
        image: {{ .Values.web.image }}:{{ .Values.web.tag }} 
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_DB
          value: {{ .Values.web.mongoDatabase | quote }}
        - name: MONGODB_HOST
          value: {{ .Release.Name }}-mongodb
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: {{ .Values.mongodb.user | quote }}
        - name: MONGODB_PASSWORD
          value: {{ .Values.mongodb.password | quote }}
