apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-movies
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-movies
  ports:
  - port: 80
    targetPort: 5000
    {{- if and (eq .Values.web.service.type "NodePort") (.Values.web.service.nodePort) }}
    nodePort: {{ .Values.web.service.nodePort }}
    {{- end }}
  type: {{ .Values.web.service.type }}
